In [1]:
import pandas as pd

In [7]:
data = pd.DataFrame({"test":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,1,0,0]})

In [8]:
data.head()

test  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write comment       0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer


In [10]:
BOW = CountVectorizer()

In [12]:
document_matrix = BOW.fit_transform(data['test'])

In [13]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [17]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [18]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]])

In [21]:
document_matrix.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?']
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [20]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()
print(X2.toarray())

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


In [25]:
bi_gram = CountVectorizer(ngram_range=(2,2))

In [26]:
tri_gram = CountVectorizer(ngram_range=(3,3))

In [34]:
mix = CountVectorizer(ngram_range=(2,2))
bi_gram = mix.fit_transform(data['test'])
print(mix.get_feature_names_out())

['ineuron watch' 'ineuron write' 'people watch' 'people write'
 'watch ineuron' 'write comment']


In [37]:
mix = CountVectorizer(ngram_range=(3,3))
tri_gram = mix.fit_transform(data['test'])
print(mix.get_feature_names_out())

['ineuron watch ineuron' 'ineuron write comment' 'people watch ineuron'
 'people write comment']


In [30]:
mix_vocab = mix.fit_transform(data['test'])
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [38]:
data = pd.DataFrame({"test":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,1,0,0]})

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['test'])
vectorizer.get_feature_names_out()
print(X.shape)

(4, 5)


In [40]:
X.toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [41]:
vectorizer.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [42]:
vectorizer.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])